# Generated by Django 4.1.5 on 2023-02-07 08:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_link', models.URLField(default='', max_length=256, verbose_name='Content link')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('is_multiple_pages', models.BooleanField(default=False, verbose_name='Is multiple pages?')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('link', models.URLField(max_length=256, verbose_name='Link')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Tag name')),
                ('class_name', models.CharField(max_length=128, verbose_name='Tag class')),
                ('category', models.CharField(choices=[('main', 'Main'), ('title', 'Title'), ('link', 'Link'), ('price', 'Price'), ('diploma', 'Diploma'), ('employment', 'Employment'), ('duration', 'Duration'), ('next_page', 'Next page button')], max_length=64)),
                ('data_pointer', models.CharField(blank=True, default='', max_length=64)),
                ('tag_order_number', models.PositiveIntegerField(default=1, verbose_name='Tag order number')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='parsers.config')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.CharField(max_length=255, unique=True, verbose_name='Link to buy')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Price')),
                ('diploma', models.BooleanField(default=False, verbose_name='Diploma?')),
                ('employment', models.BooleanField(default=False, verbose_name='Is employment guaranteed?')),
                ('duration', models.CharField(blank=True, max_length=255, verbose_name='Duration')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='parsers.source')),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to='parsers.source'),
        ),
    ]
