# Generated by Django 4.1.5 on 2023-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='data_pointer',
            field=models.CharField(default='', max_length=64),
        ),
    ]
