# Generated by Django 4.1.5 on 2023-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_tag_data_pointer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_order_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Tag order number'),
        ),
    ]
