# Generated by Django 4.1.5 on 2023-01-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_tag_tag_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='data_pointer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
