# Generated by Django 4.1.5 on 2023-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_alter_tag_data_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
